### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dmacmillan** [dieterich-lab/JACUSA#20]
Is it normal to have these kinds of exceptions in the standard out or standard error? I have them in most of my output files.

```
java.lang.ArrayIndexOutOfBoundsException: 42
        at jacusa.pileup.builder.WindowCache.addHighQualityBaseCall(WindowCache.java:72)
        at jacusa.pileup.builder.UnstrandedPileupBuilder.addHighQualityBaseCall(UnstrandedPileupBuilder.java:65)
        at jacusa.pileup.builder.AbstractPileupBuilder.processAlignmentMatch(AbstractPileupBuilder.java:537)
        at jacusa.pileup.builder.AbstractPileupBuilder.processRecord(AbstractPileupBuilder.java:401)
        at jacusa.pileup.builder.AbstractPileupBuilder.adjustWindowStart(AbstractPileupBuilder.java:178)
        at jacusa.pileup.iterator.AbstractWindowIterator.initLocation(AbstractWindowIterator.java:66)
        at jacusa.pileup.iterator.AbstractTwoSampleIterator.<init>(AbstractTwoSampleIterator.java:41)
        at jacusa.pileup.iterator.TwoSampleIterator.<init>(TwoSampleIterator.java:26)
        at jacusa.pileup.worker.TwoSampleCallWorker.buildIterator(TwoSampleCallWorker.java:44)
        at jacusa.pileup.worker.AbstractWorker.run(AbstractWorker.java:66)
```

command:

`java -jar jacusa call-2 -P UNSTRANDED,UNSTRANDED -a B,S,D,H:1,I,Y,L,M -F 1024 -f V -r jacusa.vcf -p 6 wgs_align.bam rnaseq_nodups.bam &> jacusa.log`

**Comment by dmacmillan** [comment]
bump

**Comment by piechottam** [comment]
No this is not normal.

1. pls use: -a S,D,H:1,I,Y the other filters are either redundant or will be obsolete in future versions.
2. It seems that you have Sequencing data that has Base Call Quality Score > 41
java.lang.ArrayIndexOutOfBoundsException: 42

I added support for Base Call Quality Score > 41.
Please check https://github.com/dieterich-lab/JACUSA/releases/tag/1.2.1(this is a test version).
Let them me know if this fixes your issue.

**Comment by dmacmillan** [comment]
For the `Y` pileup filter. The documentation states "Filter wrong variant calls in the vicinity of homopolymers. Default 7 (Y:length)". What do you mean by in the vicinity? Does that mean that the variant is embedded within a homopolymer of length at least 7 or does it mean that the variant could be outside of the homopolyer perhaps by a range of 7 bases?
