### ISSUE TITLE
unexpected command line complaint with -r

### ISSUE THREAD

**Issue by AMChalkie** [dieterich-lab/JACUSA#34]
java -Xmx6g -jar JACUSA_v2.0.0-RC5.jar call-1 -b Sppl2a.bed -f V -r Sppl2a.jacusa2.vcf myfile.bam
INFO    00:00:00  Computing overlap between sequence records.
--------------------------------------------------------------------------------
JACUSA2 Version: 2.0.0-RC5 call-1 -b Sppl2a.bed -f V -r Sppl2a.jacusa2.vcf myfile.bam
--------------------------------------------------------------------------------
java.lang.IllegalArgumentException: Cannot set a file type if the output is not to a file.
        at htsjdk.variant.variantcontext.writer.VariantContextWriterBuilder.setOutputFileType(VariantContextWriterBuilder.java:185)
        at jacusa.io.format.call.VCFcallWriter.<init>(VCFcallWriter.java:59)
        at jacusa.io.format.call.VCFcallFormat.createWriter(VCFcallFormat.java:41)
        at lib.worker.WorkerDispatcher.<init>(WorkerDispatcher.java:53)
        at lib.util.AbstractMethod.getWorkerDispatcherInstance(AbstractMethod.java:60)
        at lib.util.AbstractTool.run(AbstractTool.java:64)
        at jacusa.JACUSA.main(JACUSA.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)

**Comment by AMChalkie** [comment]
Note that without the -f V, an output file is produced.

**Comment by ellalalalalalala** [comment]
Hi AMChalkie, how did you solve the error? If I remove the -f V option, will my output then still be VCF, given the file ending of the output file name? In the manual it says, that the default output is BED. I did not have any comparable problems with the combination of the "-f V" and "-r file.out" option, when I used Jacusa1...

**Comment by ellalalalalalala** [comment]
I tried by removing -f V and labeling the output file as FILE.vcf... no error anymore but results in an empty output file :(

**Comment by piechottam** [comment]
I have found the problem and I will publish a new release with the fix today.

Please post issues in:
https://github.com/dieterich-lab/JACUSA2

This repository is for JACUSA**1**

**Comment by ellalalalalalala** [comment]
Hi piechottam, great, thanks a lot for your fast reply and help 🥇  Sorry for posting in the wrong repository, ich just found this thread and it was exactly my problem. :)

**Comment by piechottam** [comment]
Follow https://github.com/dieterich-lab/JACUSA2/issues/39
