### ISSUE TITLE
calmd error?

### ISSUE THREAD

**Issue by AMChalkie** [dieterich-lab/JACUSA#35]
Hi,

When running an older sample of ours, we get this error. I suggest that the software do a complete halt when it sees this.

00:00:02  Thread 1: Working on contig chr1:150384085-150384085
ERROR   00:00:02  Problem with read: E00515:95:HJ7K5ALXX:5:1218:11424:65687 in sorted/mysample.Aligned.out.srt.rg-added.dedup.calmd.bam
java.lang.IllegalArgumentException: Byte 99 unknown
        at lib.util.Base.valueOf(Base.java:72)
        at lib.recordextended.MDRecordReferenceProvider.getReferenceBase(MDRecordReferenceProvider.java:50)
        at lib.data.storage.container.SimpleMDReferenceProvider.addRecordExtended(SimpleMDReferenceProvider.java:66)
        at lib.data.storage.container.ComplexSharedStorage.addRecordExtended(ComplexSharedStorage.java:47)
        at lib.data.storage.container.UnstrandedCacheContainter.process(UnstrandedCacheContainter.java:47)
        at lib.data.storage.container.AbstractStrandedCacheContainer.process(AbstractStrandedCacheContainer.java:80)
        at lib.data.assembler.SiteDataAssembler.buildCache(SiteDataAssembler.java:57)
        at lib.util.ReplicateContainer.createIterators(ReplicateContainer.java:49)
        at lib.util.ConditionContainer.lambda$0(ConditionContainer.java:29)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at lib.util.ConditionContainer.updateWindowCoordinates(ConditionContainer.java:29)
        at lib.worker.AbstractWorker.updateReservedWindowCoordinate(AbstractWorker.java:166)
        at lib.worker.AbstractWorker.processInit(AbstractWorker.java:182)
        at lib.worker.AbstractWorker.run(AbstractWorker.java:214)

The offending read: 

samtools view sorted/mysample.Aligned.out.srt.rg-added.dedup.calmd.bam | grep HJ7K5ALXX | grep E00515 | grep "E00515:95:HJ7K5ALXX:5:2215:25246:23636"
E00515:95:HJ7K5ALXX:5:2215:25246:23636  163     chr1    127333446       255     144M    =       127333874       578     ATCACTACTAGATAGTACATCCTTATGGATCTGCAGAAATCTGCTCCAAAGGGGTGGGCTATACTTAGTGATTGTTATATATGTTTAACAGTAACAGGAAATGCATATTAACAGCAGGAATCTTTCCTGAAAGAATCCATTACA        AAFFFJFJJFFJFJFFFJJJJJJJJJA<A--<FFJAFJJJJJ7JF<-FFJ<F<-AF--AFJJFFJJJ<7JJ<AFF<FJFJJA7<FJFJJFJFFF<F-AAFJF--<AAAJFAAFJAA7)AAAFJAJ---7<<F-<A-<--7<<-7      PG:Z:MarkDuplicates     RG:Z:id NH:i:1  HI:i:1  nM:i:1  AS:i:290        NM:i:1  MD:Z:138c5
E00515:95:HJ7K5ALXX:5:2215:25246:23636  83      chr1    127333874       255     150M    =       127333446       -578    GAAAGTGCCTTTTATTTGATATTGGAATGGCTATTCAAGCTTGTTTCTTGGGACCATCTGCATGGAAAATTGTTTTCCAGCTCTTTACTCTGAGGTGGGGTTGGTCTTTGTCACTGTGGTAGATTTCCTGTATGCAGTAAAATGCTGGGT  JJJJJJJJFJJJJJJJJJJJFJJJJJJJJJJJJJJJJJFJJJJJJJJJJJFJJFJJJFJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA        PG:Z:MarkDuplicates     RG:Z:id NH:i:1  HI:i:1  nM:i:1  AS:i:290        NM:i:0  MD:Z:150

**Comment by piechottam** [comment]
1. yes, JACUSA should stop at the exception - will be fixed
2. the offending read has a lower case 'c' in the MD field (SAM format requires capital)
    MD:Z:138**c**5 
    I am hesitant to fix this. On the other hand, I know how annoying fixing such BAM files can be and samtools calmd seems to be okay with lower case 'c'

**Comment by AMChalkie** [comment]
Great. I'm doing a work-around on the bam files and that should hopefully solve things at this end.
