### ISSUE TITLE
bed format error

### ISSUE THREAD

**Issue by AMChalkie** [dieterich-lab/JACUSA#36]
processing BED files with header produces an error (solution of using a BED with no header works).

This breaks the processing:

(the example from http://genome.ucsc.edu/FAQ/FAQformat#format1)
track name=pairedReads description="Clone Paired Reads" useScore=1
chr1	3073253	3079322

INFO   	00:00:00  Computing overlap between sequence records.
java.lang.ArrayIndexOutOfBoundsException: 1
	at lib.util.coordinate.provider.BedCoordinateProvider.read(BedCoordinateProvider.java:53)
	at lib.util.coordinate.provider.BedCoordinateProvider.<init>(BedCoordinateProvider.java:33)
	at lib.util.AbstractMethod.initCoordinateProvider(AbstractMethod.java:194)
	at lib.cli.CLI.processArgs(CLI.java:181)
	at lib.util.AbstractTool.run(AbstractTool.java:53)
	at jacusa.JACUSA.main(JACUSA.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
--------------------------------------------------------------------------------
JACUSA2 Version: 2.0.0-RC5 call-1 -b mm10_ALL_GENES_plus_minus_5000bp_pos_v2.bed -r tmp ../sorted/myfile.Aligned.out.srt.rg-added.dedup.bam
--------------------------------------------------------------------------------
java.lang.NullPointerException
	at lib.worker.WorkerDispatcher.hasNext(WorkerDispatcher.java:73)
	at lib.worker.WorkerDispatcher.run(WorkerDispatcher.java:80)
	at lib.util.AbstractTool.run(AbstractTool.java:65)
	at jacusa.JACUSA.main(JACUSA.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)

**Comment by piechottam** [comment]
This will be fixed according to http://genome.ucsc.edu/FAQ/FAQformat#format1
