### ISSUE TITLE
unclear -u options

### ISSUE THREAD

**Issue by AMChalkie** [dieterich-lab/JACUSA#37]
Hi,

Again, many thanks for providing nice software.

Can I clarify the jacusa2 input parameters for -u?

java -Xmx2g -jar /mnts/bioinfo/src/JACUSA_v2.0.0-RC5.jar call-2 -u DirMult 
= OK

java -Xmx2g -jar /mnts/bioinfo/src/JACUSA_v2.0.0-RC5.jar call-2 -u calcPvalue 
java.lang.IllegalArgumentException: Unknown statistic or wrong option: calcPvalue

Also, the help could be improved by clarifying how the arguments are correctly combined:

i.e. 
Default mode
-u DirMult
Calculate a pvalue based on a chi^2 approximation of the likelihood
-u calcPvalue 
How do we, for instance, change any params in this part?
-u calcPvalue, showAlpha
-u DirMult, epsilon=0.001

 -u <MODE>                 Choose between different modes (Default: DirMult):
                           DirMult Compound Error (estimated error {0.01} + phred score)
                           |       Adjusts variant condition
                           | :epsilon       Fit achieved if |L1 - L2| < epsilon, where L1 and L2
                           correspond to old
                           |                and new likelihood respectively.
                           |                Default: 0.001
                           | :maxIterations Maximum number of iterations for Newton's method.
                           |                Default: 100
                           | :calcPvalue    Calculate a pvalue based on a chi^2 approximation of the
                           likelihood
                           |                ratio
                           | :showAlpha     Show detailed info of Newton's method in output (not in VCF
                           output).

Thanks

**Comment by piechottam** [comment]
This information is missing in CLI description - will be added.

use ":" to separate options
e.g.: -u DirMult:showAlpha:calcPvalue

**Comment by AMChalkie** [comment]
Doesn't quite seem that easy. Interestingly JACUSA still runs, but I haven't checked if the pvals get output yet.

org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --showAlpha--calcPvalue
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
        at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:407)
        at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:384)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at lib.stat.AbstractStatFactory.processCLI(AbstractStatFactory.java:72)
        at jacusa.cli.parameters.StatParameter.setFactory(StatParameter.java:65)
        at jacusa.cli.options.StatFactoryOption.process(StatFactoryOption.java:117)
        at lib.cli.CLI.processArgs(CLI.java:167)
        at lib.util.AbstractTool.run(AbstractTool.java:53)
        at jacusa.JACUSA.main(JACUSA.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
INFO    00:00:00  Computing overlap between sequence records.

**Comment by AMChalkie** [comment]
Related to this, when running -u DirMult:calcPvalue I get the following (and consistent regardless of input bam files):

--------------------------------------------------------------------------------
INFO    00:00:00  Thread 2: Working on contig chr1:3253415-3253415
INFO    00:00:00  Thread 1: Working on contig chr1:3121345-3121345
INFO    00:00:00  Thread 1: Working on contig chr1:3253892-3253892
INFO    00:00:00  Thread 2: Working on contig chr1:3262699-3262699
Exception in thread "JACUSA Worker 0" java.lang.ArrayIndexOutOfBoundsException: 2
        at lib.stat.sample.provider.pileup.AbstractEstimationSamplePileupProvider.populate(AbstractEstimationSamplePileupProvider.java:125)
        at lib.stat.sample.provider.pileup.AbstractEstimationSamplePileupProvider.createData(AbstractEstimationSamplePileupProvider.java:76)
        at lib.stat.sample.provider.pileup.AbstractEstimationSamplePileupProvider.convert(AbstractEstimationSamplePileupProvider.java:55)
        at lib.stat.dirmult.CallStat.calculate(CallStat.java:42)
        at lib.stat.AbstractStat.filter(AbstractStat.java:17)
        at jacusa.worker.CallWorker.process(CallWorker.java:46)
        at lib.worker.AbstractWorker.doWork(AbstractWorker.java:136)
        at lib.worker.AbstractWorker.processReady(AbstractWorker.java:193)
        at lib.worker.AbstractWorker.run(AbstractWorker.java:209)
Exception in thread "JACUSA Worker 1" java.lang.ArrayIndexOutOfBoundsException: 2
        at lib.stat.sample.provider.pileup.AbstractEstimationSamplePileupProvider.populate(AbstractEstimationSamplePileupProvider.java:125)
        at lib.stat.sample.provider.pileup.AbstractEstimationSamplePileupProvider.createData(AbstractEstimationSamplePileupProvider.java:76)
        at lib.stat.sample.provider.pileup.AbstractEstimationSamplePileupProvider.convert(AbstractEstimationSamplePileupProvider.java:55)
        at lib.stat.dirmult.CallStat.calculate(CallStat.java:42)
        at lib.stat.AbstractStat.filter(AbstractStat.java:17)
        at jacusa.worker.CallWorker.process(CallWorker.java:46)
        at lib.worker.AbstractWorker.doWork(AbstractWorker.java:136)
        at lib.worker.AbstractWorker.processReady(AbstractWorker.java:193)
        at lib.worker.AbstractWorker.run(AbstractWorker.java:209)
