### ISSUE TITLE
Exception in thread "Thread-0" java.lang.NullPointerException

### ISSUE THREAD

**Issue by arpitpanda01** [dieterich-lab/JACUSA#41]
Hello,
I have a sorted and indexed BAM file  from an experimental sample which I am attempting to probe for editing activity (specifically ADAR1 mediated A to G editing). My BAM was aligned to the mm10 genome, and allowed multi-mapping.
 I am looking in specific bed files corresponding to ERVs for mismatches. I use a command like the following:
I am attempting to use the following command:
java -jar JACUSA_v1.3.0.jar call-1 -b my_bed_file -r JACUSA.out my_bam_file

I end up with the following error message:
Exception in thread "Thread-0" java.lang.NullPointerException
	at jacusa.pileup.builder.AbstractPileupBuilder.<init>(AbstractPileupBuilder.java:57)
	at jacusa.pileup.builder.UnstrandedPileupBuilder.<init>(UnstrandedPileupBuilder.java:26)
	at jacusa.pileup.builder.UnstrandedPileupBuilderFactory.newInstance(UnstrandedPileupBuilderFactory.java:20)
	at jacusa.pileup.iterator.AbstractWindowIterator.createPileupBuilders(AbstractWindowIterator.java:94)
	at jacusa.pileup.iterator.AbstractOneSampleIterator.<init>(AbstractOneSampleIterator.java:28)
	at jacusa.pileup.iterator.OneSampleIterator.<init>(OneSampleIterator.java:24)
	at jacusa.pileup.worker.OneSampleCallWorker.buildIterator(OneSampleCallWorker.java:37)
	at jacusa.pileup.worker.OneSampleCallWorker.buildIterator(OneSampleCallWorker.java:1)
	at jacusa.pileup.worker.AbstractWorker.run(AbstractWorker.java:66)

I also receive a number of exceptions like the following:
java.lang.IllegalStateException: No MD field present for SAMRecord: A00873:245:HL2FWDSXY:1:1345:19416:14826_GGTTT 1/2 95b aligned read.

Is there something obvious I'm missing and needs to be fixed?

**Comment by piechottam** [comment]
Hi,

Your reads are missing the MD field - check https://samtools.github.io/hts-specs/SAMtags.pdf
[...]
String encoding mismatched and deleted reference bases, used in conjunction with the CIGAR and
SEQ fields to reconstruct the bases of the reference sequence interval to which the alignment has been
mapped. This can enable variant calling without requiring access to the entire original reference.
The MD string consists of the following items, concatenated without additional delimiter characters:
[...]

Use samtools: http://www.htslib.org/doc/samtools.html
[...]
samtools calmd [-Eeubr] [-C capQcoef] aln.bam ref.fasta

Generate the MD tag. If the MD tag is already present, this command will give a warning if the MD tag generated is different from the existing tag. Output SAM by default.

Calmd can also read and write CRAM files although in most cases it is pointless as CRAM recalculates MD and NM tags on the fly. The one exception to this case is where both input and output CRAM files have been / are being created with the no_ref option.
[...]
