### ISSUE TITLE
java.lang.IllegalArgumentException: Byte 77 unknown

### ISSUE THREAD

**Issue by camelia66** [dieterich-lab/JACUSA#42]
I'm working on the human genome (from ncbi) and I get this error message.
```

  INFO          00:07:20  Thread 1: Working on contig NC_000001.11:248300969-248400968
  INFO          00:07:20  Thread 1: Working on contig NC_000001.11:248676662-248776661
  java.lang.IllegalArgumentException: Byte 77 unknown
        at lib.util.Base.valueOf(Base.java:74)
        at lib.data.storage.container.FileReferenceProvider.getReferenceBase(FileReferenceProvider.java:90)
        at lib.data.storage.container.FileReferenceProvider.getReferenceBase(FileReferenceProvider.java:68)
        at lib.data.assembler.DataAssembler.createDefaultDataContainer(DataAssembler.java:50)
        at lib.data.assembler.DataAssembler.assembleData(DataAssembler.java:39)
        at lib.util.ReplicateContainer.getNullDataContainer(ReplicateContainer.java:61)
        at lib.util.ConditionContainer.getNullDataContainer(ConditionContainer.java:42)
        at jacusa.worker.CallWorker.createParallelData(CallWorker.java:41)
        at lib.worker.AbstractWorker.hasNext(AbstractWorker.java:111)
        at lib.worker.AbstractWorker.processReady(AbstractWorker.java:196)
        at lib.worker.AbstractWorker.run(AbstractWorker.java:213)

```
The log show that the error seems to occur at the end of the first analyzed sequence (NC_000001.11)
Any help would be greatly appreciated

**Comment by piechottam** [comment]
The error says - that your Reference is "M". (Byte 77)
I Think your reference is IUPAC M: A or C. This is not supported.
We only support ACGTN in the reference.
I am afraid you will have to change your reference.

**Comment by camelia66** [comment]
Great thank you for you prompt reply.
Is it specified within the doc? I haven't seen. If not it would be nice to add it.
